### ISSUE TITLE
Login über REST Brainstorming

### ISSUE THREAD

**Issue by CReimer** [CReimer/fhws_project#2]
HMAC (https://en.wikipedia.org/wiki/Hash-based_message_authentication_code)

**Comment by JBrunn3r** [comment]
Mennig: "Sie brauchen eigentlich nur die erste URL, schicken username und Passwort mit Basic Auth im Header. Im Erfolgsfall erhalten Sie dann ein jwt Token und das User-Objekt zurück."

![fhws auth 1](https://cloud.githubusercontent.com/assets/23078209/21495308/e9957072-cc16-11e6-8781-0d30712ac49f.png)
![fhws auth 2](https://cloud.githubusercontent.com/assets/23078209/21495315/ee84383e-cc16-11e6-88d1-4db0294f78cf.png)
![fhws auth 3](https://cloud.githubusercontent.com/assets/23078209/21495319/f15c698c-cc16-11e6-9c6f-b4c4f019bf9f.png)

**Comment by CReimer** [comment]
Ich habe darüber nachgedacht und das ganze sollte auf Clientseite passieren. Unser Server bekommt dann nur den "X-fhws-jwt-token" und kann sich darüber wieder das User Objekt beim FHWS Login-Server abholen.

Soll heißen. REST ist stateless, der jwt-token muss also bei jeder Kommunikation mitgesendet werden. Vorausgesetzt die Anfrage am Server ist nutzerspezifisch.

**Comment by CReimer** [comment]
OK. Das wird so nix. Der apistaging.fiw.fhws.de Server ist sehr restriktiv, wer drauf zugreifen darf. (Same Origin Policy). Und die Webbrowser sind da ziemlich pingelig und halten sich eben daran.

Ich versuche jetzt schon seit zwei Tagen ein ordentliches Workaround dazu zu finden. Einzige Lösung scheint mir, den Login auf dem eigenene Server zu proxyen und damit auf PHP Seite die Same-Origin-Policy zu umgehen.

**Comment by CReimer** [comment]
OK. Wenn ich jetzt versuche über den JWT Token serverseitig die Daten nochmal anzufragen klappt das nicht. Es sollte aber eigentlich. Ich sehe meinen Fehler im Moment auch nicht...

**Comment by CReimer** [comment]
Als Ablenkung von der Lernerei das hier nochmal anschaut. Der Fehler liegt darin, dass der Login-Server den Token case-sensitive behandelt. PHP verschluckt aus irgendeinem Grund aber diese Infos und alle Großbuchstaben sind später Kleinbuchstaben und das ist dann kein gültiger Token mehr.

**Comment by CReimer** [comment]
Ohh wow. Das war meine eigene Blödheit. Fix kommt gleich
