### ISSUE TITLE
Loginbutton hat keine Wirkung

### ISSUE THREAD

**Issue by CReimer** [CReimer/fhws_project#5]
Im Code sehe ich eine Loginmaske, wenn ich auf der Seite aber auf den Loginbutton drücke passiert überhaupt nichts.

**Comment by JBrunn3r** [comment]
Die Maske sollte als pop-up erscheinen, ich hätte aber vor dem fixen noch gerne abgesprochen, wer denn Zugangsrechte hat. Denkbar wäre für mich, dass man als Visitor (ohne Login) bereits Elemente der Web-App einsehen kann, aber Interaktion (Kommentare, neue Einträge etc.) einen Login benötigen.
Eine andere Möglichkeit wäre, die gesamte Web-App nur für Studenten und Dozenten zugänglich zu machen, sprich die Loginmaske ist das erste, was man zu sehen bekommt (so ähnlich wie hier: https://studentenportal.fhws.de )
Im zweiten Fall würde ich den "Login"-Button durch einen "Abmelden"-Button ersetzen.
Es lässt sich aber prinzipiell beides umsetzen. Was denkst du?

**Comment by CReimer** [comment]
Ich denke das einsehen für alle erstmal keine schlechte Idee ist. Jedes Projekt sollte dann einen Besitzer haben (Dozent) und Contributor (Studenten).

Dozenten haben das Recht neue Projekte anzulegen und ihre eigenen Projekte zu löschen
Studenten haben in erster Linie das Recht ihre fertigen Daten hochzuladen. Eventuell Beschreibungstext anpassen.

Wegen Login und Abmelden Button. Die Webapp schickt Nutzername und Passwort an den Server, der schickt einen Token zurück. Der sollte im JavaScript möglichst global zwischengespeichert sein. Ist das also der Fall, ist es ein Abmelden-Button, ist kein Token zwischengespeichert ist es ein Login-Button.

**Comment by CReimer** [comment]
Ähhm. Ich wäre jetzt so langsam darauf angewiesen.

**Comment by JBrunn3r** [comment]
Ich würde das login fenster lieber als pop-up / modal einblenden, das funktioniert aber aus Gründen die ich noch nicht nachvollziehen kann immernoch nicht richtig. Ich hab jetzt eine version gepusht, wo das login-element als einfache Seite "my-login.html" erscheint (funktioniert über den "Anmelden" button und über die Reiter).

Dass sich das ganze dann schön bedienen lässt, das werde ich zeitnah noch hinbekommen. Fürs Umsetzen und Testen des Back-Ends sollte diese Lösung vorerst reichen denke ich.

**Comment by CReimer** [comment]
Sicher, dass du gepusht hast?

**Comment by JBrunn3r** [comment]
Oops, mein Fehler. Hab committed aber nicht gepusht.

**Comment by CReimer** [comment]
Ahh. Das sieht doch nett aus. Hab gerade schonmal damit experimentiert, aber da ja alles möglichst ohne jQuery gemacht werden soll, muss ich mich erstmal in XMLHttpRequest genauer einlesen.

Im Nachhinein betrachtet hätte ich die API Demo vielleicht auch gleich ohne jQuery machen sollen...
