### ISSUE TITLE
Attribute eines Eintrags

### ISSUE THREAD

**Issue by JBrunn3r** [CReimer/fhws_project#6]
Wir sollten uns passende Attribute für die Einträge auf der Web-App so bald wie möglich überlegen.

Was meiner Meinung nach auf jeden Fall benötigt wird:
- **Eine Art "ID" als PRIMARY KEY**
- **Titel**
- **Beschreibung** (in Fließtext)
- **Typ** (Projekt/Bachelor/Master)
- **Studiengang**
- **Verantwortliche/r Dozent/en**
- **Datum** (Welche Datumsangaben sind von belang?)

Was wahrscheinlich sinnvoll wäre:
- **Daten-Uploads** (und/oder eine Gallery?)
- **Links**
- **Zeitpunkt der letzten Interaktion** (könnte für Sortierung relevant sein)

soweit ein paar Ideen.

**Comment by CReimer** [comment]
Wir haben in der Datenbank im Moment:
id - Auto increment, also als Primary Key und allgemein als Erkennungs-ID für ein Projekt
name - Titel
description - Beschreibung
status - Im Sinne von offen/abgeschlossen/fortsetzbar
supervisor - Verantwortlicher Dozent
deleted - Anstatt etwas tatsächlich zu löschen, wird es nur als gelöscht markiert
degreeProgram - Studiengang
contributor - Student (mehrzahl nötig?)
creation_date - Erstelldatum

**Comment by JBrunn3r** [comment]
Wir brauchen noch folgendes:
type - Projekt, Bachelor und/oder Master (vom Typ Enumerated String)
degreeProgram - einen oder mehrere Studiengänge (Inf, WInf und/oder EC) anstatt nur einen (vom Typ Enumerated String)
contributor - einen oder mehrere Studenten, die daran mitgewirkt haben (entweder List<String> oder direkte Verlinkung zu Studenten accounts mittels k-Nummer)

**Comment by JBrunn3r** [comment]
Der Vollständigkeit halber nochmal alle Attribute mit genauer Bezeichnung:

- id - Auto increment, also als Primary Key und allgemein als Erkennungs-ID für ein Projekt
- name - Titel
- description - Beschreibung
- status - Im Sinne von offen/abgeschlossen/fortsetzbar
- supervisor - Verantwortlicher Dozent
- deleted - Anstatt etwas tatsächlich zu löschen, wird es nur als gelöscht markiert
- degreeProgram - Studiengang
- contributor - Student/en
- creation_date - Erstelldatum
- type - Projekt, Bachelor und/oder Master
- degreeProgram - einen oder mehrere Studiengänge (Inf, WInf und/oder EC)

@CReimer stimmt das so? Falls noch mehr Attribute vorliegen bzw. neue hinzukommen, bitte diesen Eintrag editieren.

**Comment by JBrunn3r** [comment]
Frage an @CReimer:
Liegen
- status (genau einen)
- degreeProgram (einen oder mehrere)
- type (einer oder mehrere)

als enum (also vordefinierte, feste Begriffe) vor?

-----------------------------------------------

Außerdem, sind
- supervisor (einer oder mehrere)
- contributer (keiner, einer oder mehrere)

verknüpft mit jwt-token? oder Freitext?
